x-logging: &default-logging
  options:
    max-size: "10m"
  driver: json-file

services:
  app:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - 80
    volumes:
      - ./:/var/www/html:delegated
    environment:
      TZ: "Europe/Moscow"
    depends_on:
      - php
    networks:
      - laravel
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.${TRAEFIK_SERVICE}.rule=Host(`${DOCKER_DOMAIN}`)"
      - "traefik.http.routers.${TRAEFIK_SERVICE}.entrypoints=web"
      - "traefik.http.middlewares.https_redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.${TRAEFIK_SERVICE}.middlewares=https_redirect"
      - "traefik.http.routers.${TRAEFIK_SERVICE}-https.entrypoints=websecure"
      - "traefik.http.routers.${TRAEFIK_SERVICE}-https.rule=Host(`${DOCKER_DOMAIN}`)"
      - "traefik.http.routers.${TRAEFIK_SERVICE}-https.tls=true"
      - "traefik.http.routers.${TRAEFIK_SERVICE}-https.tls.certresolver=le"
    logging: *default-logging

  pgsql:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: "${DB_USERNAME}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_DATABASE}"
      TZ: "Europe/Moscow"
    volumes:
      - pgsql_data:/var/lib/postgresql/data:delegated
    networks:
      - laravel
      - traefik-public
    logging: *default-logging

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      target: app
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    expose:
      - 9000
    volumes:
      - ./:/var/www/html:delegated
    depends_on:
      - pgsql
      - redis
    environment:
      TZ: Europe/Moscow
    networks:
      - laravel
      - traefik-public
    logging: *default-logging

  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - ./docker/redis:/data:delegated
    expose:
      - 6379
    environment:
      TZ: Europe/Moscow
    networks:
      - laravel
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      retries: 3
      timeout: 5s
    logging: *default-logging

  composer:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      target: app
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./:/var/www/html:delegated
      - ../packages/:/var/www/packages:delegated
      - ~/.ssh/:/home/laravel/.ssh
    entrypoint: ["composer"]
    environment:
      TZ: Europe/Moscow
    networks:
      - laravel
    logging: *default-logging

  npm:
    image: node:current-alpine
    volumes:
      - ./:/var/www/html
    expose:
      - 3000
      - 3001
      - 5173
    working_dir: /var/www/html
    entrypoint: ["npm"]
    command: ["run", "dev"]
    environment:
      TZ: Europe/Moscow
    networks:
      - laravel
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.${TRAEFIK_SERVICE}-npm.rule=Host(`${DOCKER_DOMAIN}`)"
      - "traefik.http.services.${TRAEFIK_SERVICE}-npm.loadbalancer.server.port=3000"
      - "traefik.http.services.${TRAEFIK_SERVICE}-npm.loadbalancer.server.port=3001"
      - "traefik.http.services.${TRAEFIK_SERVICE}-npm.loadbalancer.server.port=5173"
    logging: *default-logging

  artisan:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      target: app
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./:/var/www/html:delegated
    depends_on:
      - pgsql
      - redis
    entrypoint: ["php", "/var/www/html/artisan"]
    environment:
      TZ: Europe/Moscow
    networks:
      - laravel
    logging: *default-logging

  mailhog:
    image: mailhog/mailhog:latest
    expose:
      - 1025
      - 8025
    environment:
      TZ: Europe/Moscow
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.${TRAEFIK_SERVICE}-mailhog.rule=Host(`${DOCKER_DOMAIN}`) && Path(`/mailhog`)"
      - "traefik.http.services.${TRAEFIK_SERVICE}-mailhog.loadbalancer.server.port=8025"
      - "traefik.http.routers.${TRAEFIK_SERVICE}-mailhog.service=${TRAEFIK_SERVICE}-mailhog"
      - "traefik.http.routers.${TRAEFIK_SERVICE}-mailhog.entrypoints=websecure"
      - "traefik.http.routers.${TRAEFIK_SERVICE}-mailhog.tls=true"
      - "traefik.http.routers.${TRAEFIK_SERVICE}-mailhog.tls.certresolver=le"
    networks:
      - laravel
      - traefik-public
    logging: *default-logging

  scheduler:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      target: app
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./:/var/www/html:delegated
    depends_on:
      - pgsql
      - redis
    environment:
      TZ: Europe/Moscow
    networks:
      - laravel
    entrypoint: ["/var/www/html/docker/php/schedule_run.sh"]
    logging: *default-logging

  horizon:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
      target: horizon
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./:/var/www/html:delegated
      - ./docker/php/supervisord.d/horizon.conf:/etc/supervisord.d/horizon.conf
    depends_on:
      - pgsql
      - redis
    environment:
      TZ: Europe/Moscow
    networks:
      - laravel
    logging: *default-logging

  adminer:
    image: adminer
    restart: unless-stopped
    expose:
      - 8080
    depends_on:
      - pgsql
    networks:
      - laravel
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-public"
      - "traefik.http.routers.${TRAEFIK_SERVICE}-adminer.rule=Host(`${DOCKER_DOMAIN}`) && Path(`/adminer`)"
      - "traefik.http.routers.${TRAEFIK_SERVICE}-adminer.service=${TRAEFIK_SERVICE}-adminer"
      - "traefik.http.routers.${TRAEFIK_SERVICE}-adminer.entrypoints=websecure"
      - "traefik.http.routers.${TRAEFIK_SERVICE}-adminer.tls=true"
      - "traefik.http.routers.${TRAEFIK_SERVICE}-adminer.tls.certresolver=le"
      - "traefik.http.services.${TRAEFIK_SERVICE}-adminer.loadbalancer.server.port=8080"
    logging: *default-logging

networks:
  laravel:
  traefik-public:
    name: "traefik-public"
    external: true

volumes:
  pgsql_data:
